/**
 * EasyWeb Ad Blocker — Network Filter Lists
 *
 * Plain source of truth for the declarativeNetRequest rule-sets. `build.js`
 * compiles each list below into a valid `dist/rules/<file>` JSON rule-set, so
 * filter entries stay readable and rule ids can never collide.
 *
 * Entry syntax (Adblock-compatible subset understood by the compiler):
 *   "||example.com^"   anchored domain filter   -> block
 *   "@@||example.com^" exception               -> allow
 *   "example.com/path" plain substring filter  -> block
 *   "/^https?:\\/\\/ads\\./" regular expression   -> block
 *
 * Object form allows per-entry overrides:
 *   { f: "||ads.example.com^", t: ["script"], p: 2 }
 */

/** Resource types blocked for ad / tracker payloads (main document excluded). */
const PAYLOAD_TYPES = [
  'sub_frame',
  'stylesheet',
  'script',
  'image',
  'font',
  'object',
  'xmlhttprequest',
  'ping',
  'media',
  'websocket',
  'other'
];

/** Types blocked for popup / redirect domains (the top document included). */
const NAVIGATION_TYPES = ['main_frame', 'sub_frame'];

/* ------------------------------------------------------------------ */
/* 1. Advertising networks and ad-serving platforms                    */
/* ------------------------------------------------------------------ */
const ADS = [
  // Google ad stack
  '||doubleclick.net^',
  '||googlesyndication.com^',
  '||googleadservices.com^',
  '||adservice.google.com^',
  '||googletagservices.com^',
  '||googletagmanager.com^',
  '||2mdn.net^',
  '||admob.com^',
  '||adsensecustomsearchads.com^',
  '||app-measurement.com^',
  '||pagead2.googlesyndication.com^',
  '||tpc.googlesyndication.com^',
  '||securepubads.g.doubleclick.net^',
  '||pubads.g.doubleclick.net^',

  // Major exchanges, SSPs and DSPs
  '||adnxs.com^',
  '||adnxs-simple.com^',
  '||adsrvr.org^',
  '||advertising.com^',
  '||amazon-adsystem.com^',
  '||criteo.com^',
  '||criteo.net^',
  '||pubmatic.com^',
  '||rubiconproject.com^',
  '||magnite.com^',
  '||openx.net^',
  '||openx.com^',
  '||smartadserver.com^',
  '||smartclip.net^',
  '||casalemedia.com^',
  '||contextweb.com^',
  '||emxdgt.com^',
  '||improvedigital.com^',
  '||indexww.com^',
  '||loopme.me^',
  '||media.net^',
  '||nativo.com^',
  '||onetag-sys.com^',
  '||pubnative.net^',
  '||quantcast.com^',
  '||quantcast.mgr.consensu.org^',
  '||seedtag.com^',
  '||smadex.com^',
  '||stickyadstv.com^',
  '||tremorhub.com^',
  '||triplelift.com^',
  '||undertone.com^',
  '||videoamp.com^',
  '||yieldlab.net^',
  '||zemanta.com^',
  '||bidswitch.net^',
  '||districtm.io^',
  '||sonobi.com^',
  '||sovrn.com^',
  '||gumgum.com^',
  '||33across.com^',
  '||rhythmone.com^',
  '||adform.net^',
  '||flashtalking.com^',
  '||serving-sys.com^',
  '||sizmek.com^',
  '||zedo.com^',
  '||adzerk.net^',
  '||admedia.com^',
  '||adbutler.com^',
  '||adition.com^',
  '||adtech.de^',
  '||adtechus.com^',
  '||adroll.com^',
  '||yieldmo.com^',
  '||spotxchange.com^',
  '||spotx.tv^',
  '||widespace.com^',
  '||adkernel.com^',
  '||adyoulike.com^',
  '||ligatus.com^',
  '||plista.com^',
  '||dable.io^',
  '||engageya.com^',
  '||stroeer.de^',
  '||adpushup.com^',
  '||adpushup.net^',
  '||snapads.com^',
  '||applovin.com^',
  '||chartboost.com^',
  '||vungle.com^',
  '||adcolony.com^',
  '||inmobi.com^',
  '||smaato.net^',
  '||mopub.com^',
  '||startapp.com^',
  '||unityads.unity3d.com^',
  '||tapjoy.com^',
  '||fyber.com^',
  '||supersonicads.com^',
  '||adswizz.com^',
  '||adikteev.com^',
  '||adsafeprotected.com^',
  '||moatads.com^',
  '||iasds01.com^',
  '||doubleverify.com^',
  '||adlightning.com^',
  '||confiant-integrations.net^',
  '||coadvertise.com^',

  // Publisher ad platforms / monetisation wrappers
  '||ezoic.net^',
  '||ezoic.com^',
  '||mediavine.com^',
  '||adthrive.com^',
  '||playwire.com^',
  '||monumetric.com^',
  '||snigelweb.com^',
  '||freestar.com^',
  '||sortable.com^',
  '||adplugg.com^',
  '||broadstreetads.com^',
  '||blogher.com^',
  '||shemedia.com^',
  '||cafemedia.com^',
  '||setupad.com^',
  '||nitropay.com^',
  '||venatusmedia.com^',
  '||adnimation.com^',

  // Video / native advertising
  '||teads.tv^',
  '||sharethrough.com^',
  '||connatix.com^',
  '||primis.tech^',
  '||unrulymedia.com^',
  '||vidazoo.com^',
  '||anyclip.com^',
  '||springserve.com^',
  '||innovid.com^',
  '||freewheel.tv^',
  '||fwmrm.net^',
  '||adap.tv^',
  '||tubemogul.com^',
  '||brightcove.com/ads^',
  '||imrworldwide.com^',
  '||aniview.com^',
  '||brid.tv^',
  '||vi.ai^',
  '||vidgyor.com^',

  // Content recommendation widgets
  '||outbrain.com^',
  '||taboola.com^',
  '||taboolanews.com^',
  '||taboolasyndication.com^',
  '||mgid.com^',
  '||revcontent.com^',
  '||content.ad^',
  '||adblade.com^',
  '||nativeads.com^',
  '||ntv.io^',
  '||zergnet.com^',
  '||dianomi.com^',
  '||yieldbot.com^',

  // Pop-under / aggressive ad networks
  '||propellerads.com^',
  '||propellerpops.com^',
  '||onclickads.net^',
  '||onclckds.com^',
  '||popads.net^',
  '||popcash.net^',
  '||adcash.com^',
  '||exoclick.com^',
  '||exosrv.com^',
  '||realsrv.com^',
  '||juicyads.com^',
  '||trafficjunky.com^',
  '||trafficjunky.net^',
  '||trafficstars.com^',
  '||adtng.com^',
  '||clickadu.com^',
  '||adsterra.com^',
  '||hilltopads.net^',
  '||ad-maven.com^',
  '||admaven.com^',
  '||adnium.com^',
  '||clickaine.com^',
  '||bidvertiser.com^',
  '||zeropark.com^',
  '||voluum.com^',
  '||clickmagick.com^',
  '||trafficfactory.biz^',
  '||tsyndicate.com^',
  '||twinrdack.com^',
  '||pushnotification.website^',
  '||bestcontentfood.top^',
  '||pemsrv.com^',
  '||profitableratecpm.com^',
  '||highperformancecpm.com^',
  '||adultmoda.com^',
  '||ero-advertising.com^',
  '||adspyglass.com^',
  '||magsrv.com^',

  // Link shorteners / interstitial redirectors
  '||adf.ly^',
  '||shorte.st^',
  '||linkvertise.com^',
  '||ouo.io^',
  '||adfoc.us^',
  '||bc.vc^',
  '||clk.sh^',
  '||shrinkme.io^',
  '||shrinkearn.com^',
  '||exe.io^',
  '||fc.lc^',
  '||za.gl^',
  '||cuty.io^',
  '||gplinks.co^',
  '||mdisk.me^',
  '||droplink.co^',

  // Iranian ad networks (Yektanet, MediaAd, Sabavision, Najva, Kaprila, etc.)
  '||yektanet.com^',
  '||ynr4.net^',
  '||ynr5.net^',
  '||yektasource.com^',
  '||mediaad.org^',
  '||sabavision.com^',
  '||najva.com^',
  '||kaprila.com^',
  '||daart.org^',
  '||daart.ir^',
  '||tavoos.net^',
  '||anjoman.org^',
  '||vatanclick.ir^',
  '||clickyab.com^',
  '||magnet.ir^',
  '||raykaad.com^'
];

/* ------------------------------------------------------------------ */
/* 2. Trackers, analytics and fingerprinting                           */
/* ------------------------------------------------------------------ */
const TRACKERS = [
  // Analytics platforms
  '||google-analytics.com^',
  '||analytics.google.com^',
  '||googletagmanager.com/gtm^',
  '||ssl.google-analytics.com^',
  '||region1.google-analytics.com^',
  '||matomo.cloud^',
  '||matomo.org^',
  '||piwik.pro^',
  '||statcounter.com^',
  '||histats.com^',
  '||extremetracking.com^',
  '||sitemeter.com^',
  '||clicky.com^',
  '||gostats.com^',
  '||woopra.com^',
  '||chartbeat.com^',
  '||chartbeat.net^',
  '||parsely.com^',
  '||cxense.com^',
  '||mParticle.com^',
  '||mparticle.com^',
  '||kissmetrics.com^',
  '||kissmetrics.io^',

  // Behavioural analytics / session replay
  '||hotjar.com^',
  '||hotjar.io^',
  '||clarity.ms^',
  '||mouseflow.com^',
  '||luckyorange.com^',
  '||luckyorange.net^',
  '||fullstory.com^',
  '||smartlook.com^',
  '||smartlook.cloud^',
  '||inspectlet.com^',
  '||crazyegg.com^',
  '||sessioncam.com^',
  '||logrocket.com^',
  '||logrocket.io^',
  '||userpilot.com^',
  '||pendo.io^',
  '||walkme.com^',
  '||quantummetric.com^',
  '||contentsquare.net^',
  '||decibelinsight.net^',
  '||glassboxdigital.io^',

  // Product analytics & experimentation
  '||mixpanel.com^',
  '||amplitude.com^',
  '||segment.io^',
  '||segment.com^',
  '||heapanalytics.com^',
  '||posthog.com^',
  '||plausible.io^',
  '||split.io^',
  '||optimizely.com^',
  '||vwo.com^',
  '||abtasty.com^',
  '||kameleoon.com^',
  '||dynamicyield.com^',
  '||conductrics.com^',
  '||statsig.com^',

  // Mobile / attribution SDKs
  '||branch.io^',
  '||adjust.com^',
  '||appsflyer.com^',
  '||kochava.com^',
  '||singular.net^',
  '||tenjin.com^',
  '||attribution.report^',
  '||appmetrica.yandex.net^',

  // Data brokers / identity graphs / DMPs
  '||demdex.net^',
  '||krxd.net^',
  '||bluekai.com^',
  '||oracleinfinity.io^',
  '||addthis.com^',
  '||sharethis.com^',
  '||crwdcntrl.net^',
  '||exelator.com^',
  '||agkn.com^',
  '||ml314.com^',
  '||rlcdn.com^',
  '||tapad.com^',
  '||turn.com^',
  '||mathtag.com^',
  '||quantserve.com^',
  '||scorecardresearch.com^',
  '||comscore.com^',
  '||nielsen.com^',
  '||exelate.com^',
  '||zeotap.com^',
  '||liveramp.com^',
  '||thetradedesk.com^',
  '||adsrvr.org^',
  '||sitescout.com^',
  '||simpli.fi^',
  '||owneriq.net^',
  '||neustar.biz^',
  '||signal.co^',

  // Social trackers & embedded widgets
  '||platform.twitter.com^',
  '||syndication.twitter.com^',
  '||connect.facebook.net^',
  '||pixel.facebook.com^',
  '||facebook.com/tr^',
  '||graph.facebook.com^',
  '||analytics.tiktok.com^',
  '||business-api.tiktok.com^',
  '||ads.linkedin.com^',
  '||px.ads.linkedin.com^',
  '||snap.licdn.com^',
  '||analytics.pinterest.com^',
  '||ct.pinterest.com^',
  '||sc-static.net^',
  '||tr.snapchat.com^',
  '||sc-analytics.appspot.com^',
  '||bat.bing.com^',
  '||c.bing.com^',
  '||clarity.microsoft.com^',
  '||ads.reddit.com^',
  '||events.reddit.com^',
  '||analytics.yahoo.com^',
  '||geo.yahoo.com^',
  '||mc.yandex.ru^',
  '||metrika.yandex.ru^',
  '||top-fwz1.mail.ru^',
  '||ad.mail.ru^',
  '||vk.com/rtrg^',
  '||top100.ru^',

  // Error / performance telemetry that doubles as tracking
  '||newrelic.com^',
  '||nr-data.net^',
  '||bugsnag.com^',
  '||sentry-cdn.com^',
  '||datadoghq-browser-agent.com^',
  '||raygun.io^',
  '||trackjs.com^',
  '||js.monitor.azure.com^',

  // Lead-gen / visitor identification
  '||zoominfo.com^',
  '||clearbit.com^',
  '||fullcontact.com^',
  '||lusha.com^',
  '||hunter.io^',
  '||getkoala.com^',
  '||leadfeeder.com^',
  '||albacross.com^',
  '||visistat.com^',
  '||trackingclick.net^',
  '||tracking101.com^',
  '||visitor-track.com^',

  // Push notification / re-engagement SDKs
  '||onesignal.com^',
  '||pushengage.com^',
  '||izooto.com^',
  '||webpushr.com^',
  '||sendpulse.com^',
  '||cleverpush.com^',
  '||pushwoosh.com^',
  '||pushnami.com^',
  '||notifystatistics.com^',
  '||pushcrew.com^',
  '||foxpush.net^',
  '||gravitec.net^'
];

/* ------------------------------------------------------------------ */
/* 3. Popup, pop-under and forced-redirect destinations                */
/*    These block the top-level document too, which is what stops the   */
/*    "click the video -> new tab opens" behaviour at the network layer.*/
/* ------------------------------------------------------------------ */
const POPUPS = [
  // Pop-under networks
  '||popads.net^',
  '||popcash.net^',
  '||propellerads.com^',
  '||propellerpops.com^',
  '||onclickads.net^',
  '||onclckds.com^',
  '||onclckpro.com^',
  '||popmyads.com^',
  '||popunder.ru^',
  '||popuptraffic.com^',
  '||adcash.com^',
  '||clickadu.com^',
  '||adsterra.com^',
  '||hilltopads.net^',
  '||ad-maven.com^',
  '||admaven.com^',
  '||adnium.com^',
  '||trafficstars.com^',
  '||tsyndicate.com^',
  '||exoclick.com^',
  '||exosrv.com^',
  '||realsrv.com^',
  '||juicyads.com^',
  '||trafficjunky.com^',
  '||trafficjunky.net^',
  '||adtng.com^',
  '||ero-advertising.com^',
  '||adspyglass.com^',
  '||magsrv.com^',
  '||pemsrv.com^',
  '||profitableratecpm.com^',
  '||highperformancecpm.com^',
  '||highcpmgate.com^',
  '||bestcontentfood.top^',
  '||pushnotification.website^',
  '||pushedwebnews.com^',
  '||news-push.com^',
  '||adplus.co.id^',
  '||adserversolutions.com^',
  '||deloplen.com^',
  '||zeybuxah.com^',
  '||netadsrv.com^',
  '||adserviceretry.com^',

  // Scam / fake-download / "your device is infected" redirectors
  '||yourdeviceisinfected.com^',
  '||system-alert.net^',
  '||viruswarning.net^',
  '||mackeeper.com^',
  '||totalav.com^',
  '||adwarealert.com^',
  '||cleanmymac.com^',
  '||driverupdate.net^',
  '||outdatedbrowser.com^',
  '||update-your-browser.com^',
  '||browser-update.org^',
  '||flashplayer-update.com^',
  '||adobe-flash-update.com^',

  // Interstitial / gateway redirectors
  '||adf.ly^',
  '||shorte.st^',
  '||linkvertise.com^',
  '||ouo.io^',
  '||adfoc.us^',
  '||bc.vc^',
  '||clk.sh^',
  '||shrinkme.io^',
  '||shrinkearn.com^',
  '||exe.io^',
  '||fc.lc^',
  '||za.gl^',
  '||cuty.io^',
  '||gplinks.co^',
  '||mdisk.me^',
  '||droplink.co^',
  '||shortearn.eu^',
  '||earn4link.in^',
  '||link1s.com^',
  '||tii.ai^',
  '||sub2unlock.com^',
  '||sub2unlock.net^',
  '||rekonise.com^',

  // Clickbait / chumbox destinations
  '||taboola.com^',
  '||outbrain.com^',
  '||mgid.com^',
  '||revcontent.com^',
  '||zergnet.com^',
  '||dianomi.com^',
  '||content.ad^',
  '||adblade.com^',
  '||nativeads.com^',
  '||ntv.io^',

  // Crypto-mining / jacking scripts that hijack the tab
  '||coinhive.com^',
  '||coin-hive.com^',
  '||jsecoin.com^',
  '||crypto-loot.com^',
  '||cryptoloot.pro^',
  '||coinimp.com^',
  '||webminepool.com^',
  '||minero.cc^',
  '||coinpot.co^',
  '||monerise.com^',
  '||webmine.cz^',
  '||authedmine.com^',

  // Iranian popups and ad redirects
  '||yektanet.com^',
  '||ynr4.net^',
  '||ynr5.net^',
  '||mediaad.org^',
  '||sabavision.com^',
  '||najva.com^',
  '||tavoos.net^',
  '||vatanclick.ir^',

  // Aggressive pop-unders & ad redirectors
  '||highcpmrevenuenetwork.com^',
  '||profitablecpmrate.com^',
  '||asgardianm.com^',
  '||alwingulla.com^',
  '||whomeetoget.com^',
  '||syndication.exdynsrv.com^'
];

/* ------------------------------------------------------------------ */
/* 4. Annoyances — anti-adblock walls, social widgets, consent nags    */
/* ------------------------------------------------------------------ */
const ANNOYANCES = [
  // Anti-adblock scripts (blocked so the wall never renders)
  '||adblock-detect.com^',
  '||adblockdetect.xyz^',
  '||adblockdetector.com^',
  '||antiadblock.com^',
  '||blockadblock.com^',
  '||detectadblock.com^',
  '||adblocker-detect.com^',
  '||adblockanalytics.com^',
  '||adblock-detector.com^',
  '||pagefair.com^',
  '||pagefair.net^',
  '||blockthrough.com^',
  '||sourcepoint.mgr.consensu.org^',
  '||cmp.inmobi.com^',
  '||fuckadblock.com^',
  '||fuckadblock.online^',

  // Bait scripts: redirect to a bundled no-op so the detector's probe
  // succeeds and the "please disable your ad blocker" wall never appears.
  { r: '^https?://[^/]+/(?:ads?|advert|adframe|ad-banner|bait|adblocker)\\.js(?:\\?|$)', t: ['script'], redirect: 'noop' },
  { r: '^https?://[^/]+/(?:detectadblock|blockadblock|fuckadblock|adblock[-_]?(?:detect|check|test))\\.js(?:\\?|$)', t: ['script'], redirect: 'noop' },
  { r: '^https?://[^/]+/pagead/js/adsbygoogle\\.js(?:\\?|$)', t: ['script'], redirect: 'noop' },
  { r: '^https?://pagead2\\.googlesyndication\\.com/pagead/js/adsbygoogle\\.js(?:\\?|$)', t: ['script'], redirect: 'noop' },
  { r: '^https?://[^/]+/(?:js/)?(?:ads|advert|banner)(?:[-_.]?min)?\\.js(?:\\?|$)', t: ['script'], redirect: 'noop' },

  // Consent-management popups (cookie walls)
  '||onetrust.com^',
  '||cookielaw.org^',
  '||quantcast.mgr.consensu.org^',
  '||consentmanager.net^',
  '||consensu.org^',
  '||trustarc.com^',
  '||truste.com^',
  '||evidon.com^',
  '||crownpeak.com^',
  '||usercentrics.eu^',
  '||usercentrics.com^',
  '||iubenda.com^',
  '||osano.com^',
  '||termly.io^',
  '||cookiebot.com^',
  '||cookiefirst.com^',
  '||klaro.org^',

  // Social / engagement widgets
  '||addtoany.com^',
  '||shareaholic.com^',
  '||addthis.com^',
  '||sharethis.com^',
  '||sumo.com^',
  '||sumome.com^',
  '||getsocial.io^',
  '||po.st^',
  '||gigya.com^',
  '||janrain.com^',

  // Chat / survey / engagement overlays
  '||intercom.io^',
  '||intercomcdn.com^',
  '||drift.com^',
  '||driftt.com^',
  '||livechatinc.com^',
  '||zendesk.com/embeddable^',
  '||tidio.co^',
  '||tawk.to^',
  '||crisp.chat^',
  '||survicate.com^',
  '||hotjar.com/surveys^',
  '||qualtrics.com^',
  '||typeform.com/embed^',
  '||usabilla.com^',
  '||getfeedback.com^',
  '||wisepops.com^',
  '||sleeknote.com^',
  '||privy.com^',
  '||justuno.com^',
  '||optinmonster.com^',
  '||mailmunch.co^'
];

/** Compiled by build.js into the static rule-sets declared in manifest.json. */
export const FILTER_LISTS = {
  ads: {
    id: 'easyweb_ads',
    file: 'ads.json',
    resourceTypes: PAYLOAD_TYPES,
    filters: ADS
  },
  trackers: {
    id: 'easyweb_trackers',
    file: 'trackers.json',
    resourceTypes: PAYLOAD_TYPES,
    filters: TRACKERS
  },
  popups: {
    id: 'easyweb_popups',
    file: 'popups.json',
    resourceTypes: NAVIGATION_TYPES,
    filters: POPUPS
  },
  annoyances: {
    id: 'easyweb_annoyances',
    file: 'annoyances.json',
    resourceTypes: PAYLOAD_TYPES,
    filters: ANNOYANCES
  }
};
